### ISSUE TITLE
Unhandled Rejection (Error): Request listener already exists for xcomponent_allow_delegate_ppcheckout on domain * for wildcard window

### ISSUE THREAD

**Issue by leotm** [andrewangelle/react-paypal-button#2]
Getting this
<img width="1640" alt="screen shot 2018-10-09 at 12 55 44" src="https://user-images.githubusercontent.com/1881059/46668024-38fd8480-cbc3-11e8-82f6-707e02bc2083.png">

Any ideas?

I've created a component like so:

```
import React, { Component } from 'react'
import PayPalButton from 'react-paypal-button'

interface Props {
  env: string
  sandboxID: string
  amount: string
  currency: string
  commit: boolean
}

export default class App extends Component<Props> {
  render() {
    return (
      <PayPalButton
        env={this.props.env}
        sandboxID={this.props.sandboxID}
        amount={this.props.amount}
        currency={this.props.currency}
        commit={true}
      />
    )
  }
}
```

Then later import and render it like so:

```
<PayPalButton
  env="sandbox"
  sandboxID="My-SandboxID"
  amount="0.01"
  currency="GBP"
  commit={true}
/>
```

"react": "16.5.2",
"next": "^7.0.1",
macOS High Sierra 10.13.6
Chrome Version 69.0.3497.1 (Official Build) (64-bit)

Thanks

**Comment by leotm** [comment]
I've also tried plain and simple:

```
import PayPalButton from 'react-paypal-button'
              <PayPalButton
                env="sandbox"
                sandboxID="My-SandboxID"
                amount="0.01"
                currency="GBP"
                commit={true}
              />
```

**Comment by andrewangelle** [comment]
@leotm sorry for the late reply.
I think this is a compatibility issue between react v16 and/or typescript and `react-paypal-button`.
I'll take a closer look in the next few days.

**Comment by papaponmx** [comment]
Did you get to solve it?

**Comment by andrewangelle** [comment]
@papaponmx @leotm Issue should be fixed now. Try using the latest version.

**Comment by leotm** [comment]
@andrewangelle Great thanks, will do pronto when back on my machine
@papaponmx let me know how it goes too

**Comment by papaponmx** [comment]
I ended up using a custom component 😅

**Comment by andrewangelle** [comment]
Closing

Fixed by:
* https://github.com/andrewangelle/react-paypal-button/pull/4
* https://github.com/andrewangelle/react-paypal-button/commit/78e2dc8a698c658212de83192c6eece4c3c205db
