### ISSUE TITLE
SSR Server side rendering error

### ISSUE THREAD

**Issue by Distil62** [andrewangelle/react-paypal-button#3]
Hello, 

When i try to render the button is SSR i have the error window is undefined

Temp fix : 
```js
class Paypal extends Component {

constructor(props) {
if (typeof window !== 'undefined') {
	PaypalButton = require('react-paypal-button');
}
}
}
```

**Comment by Kaukov** [comment]
This is an issue with Webpack and this has been known to be the hackfix for it. I don't think @andrewangelle can do anything about it since he's just abstracting on top of PayPal's button for easier use

**Comment by andrewangelle** [comment]
@Distil62 Yes, see Kaukov's reply above. You seem to have the right fix for it.

**Comment by andrewangelle** [comment]
Closing this for now. Feel free to open a new issue if anything changes.
