### ISSUE TITLE
Use with React Native

### ISSUE THREAD

**Issue by JamieCorkhill** [andrewangelle/react-paypal-button#7]
Can this component be used or modified as to work with React Native? I can't find any PayPal Smart Buttons for React Native, and the official PayPal Documentation only provide a method by which to use them on the web.

Thanks.

**Comment by andrewangelle** [comment]
@JamieCorkhill I highly doubt it. My understanding is that the base components are different in react-dom versus react-native, and the paypal-checkout library that this is built on top of assumes react-dom.

However, check out this repo https://github.com/smarkets/react-native-paypal
