### ISSUE TITLE
How to set options to display multiple funding sources?

### ISSUE THREAD

**Issue by actelligent-team** [andrewangelle/react-paypal-button#8]
To make card or credit buttons, how to set props?

**Comment by andrewangelle** [comment]
@actelligent-team. The button launches paypal's express checkout. After the user logs in, the payment screen in express checkout will display the user's available purchase sources. 

Apologies for the oversized picture, but you can see what I'm referring to below.

![paypalpayment](https://user-images.githubusercontent.com/24420033/61671863-fd91f980-acae-11e9-9e5d-0833ece2f368.PNG)
